### PR TITLE
Testing out PRs

### PR DESCRIPTION
**Pull request by WalkingFishes**
I made a simple change to the Hero class replacing "2021" with "Insert Year Here" in order to test out Pull-Requests.

### CODE REVIEW

**Review by betsystevens — CHANGES_REQUESTED** [review]
Good improvement.

To avoid confusing a placeholder with an input field, use the word ```placeholder``` in the inner text.

**Comment by WalkingFishes** [comment]
Good suggestion.  Will do.

Separately, should I create an issue to get the date from the current system time or do you want to create the issue?

**Comment by betsystevens** [comment]
You can create the issue and I'll assign it to you.

**Review by betsystevens — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
